#!/usr/bin/env bash
# script that transfers a file from our client to a server

# store number of args
len=$#

if (($len <= 3)); then
	echo 'USAGE: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit
fi
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=No "$PATH_TO_FILE" "$USERNAME@$IP":~/
