#!/usr/bin/env bash
#generates a MySQL dump and creates a compressed archive out of it
sudo mysqldump -uroot -p"$1" --all-databases > backup.sql
sudo tar -cvzf "$(date '+%d-%m-%Y').tar.gz" backup.sql
