#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd
# displaying only the username, user id and home directory path for the user

while read -r line
do
	echo "$line" | cut -d: -f1,4,7
done < "/etc/passwd"
