#!/usr/bin/env bash
# Script that displays 10 times Best School
i=1
while (( i <= 10 ))
do
  if (( i == 4 ))
  then
  	echo "bad luck"
  elif (( i == 8 ))
  then
  	echo "good luck"
  else
  	echo "Best School"
  fi
  ((i++))
done
