#!/usr/bin/env bash
# using the while loop, display the time for 12 hours and 59 minutes
# using the while loop
# display hours from 0 to 12.
# display minutes from 1 to 59.
i=0
while (( i < 13 ))
do
	echo "Hour: $i"
	j=1
	while ((j < 60))
	do
		echo $j
		((j++))
	done
	((i++))
done
