#!/usr/bin/env bash
# Script that displays content of current directory
# displaying in a list format where only the part of the name after the first dash is displayed

for i in *
do
	echo "$i" | cut -d'-' -f2
done
