#!/usr/bin/env bash
# Script that gives information about the school file
# if the file exists then prints "school file exists"
# if the file does not exist: school file does not exist
file="school"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school is empty"
	fi
	if [ -f "$file" ]; then
                echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
